[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "CHASM"
version = "0.1.0"
dependencies = [
    "aiapy>=0.11.0",
    "astropy>=6.0.0",
    "beautifulsoup4>=4.12.0",
    "gdown>=5.2.1",
    "ipykernel>=6.30.1",
    "matplotlib>=3.10.5",
    "numpy>=1.26.0",
    "opencv-python>=4.8.0",
    "pillow>=10.0.0",
    "pypdfium2>=4.26.0",
    "python-dotenv>=1.1.1",
    "requests>=2.31.0",
    "segment-anything>=1.0",
    "sunpy[map]>=7.0.1",
    "torch",
    "torchvision",
    "tqdm>=4.66.0",
]
requires-python = ">=3.13"
authors = [
    {name = "Cutter J. Beck", email = "cjbeck@alum.wpi.edu"},
    {name = "Evan G. Smith", email = "egsmith@wpi.edu"},
    {name = "Khagendra Katuwal", email = "katuwal@nmsu.edu"},
    {name = "Rudra Kafle", email = "rpk101@wpi.edu"},
    {name = "Jacob Whitehill", email = "jrwhitehill@wpi.edu"},
]
maintainers = [
    {name = "Cutter J. Beck", email = "cjbeck@alum.wpi.edu"},
    {name = "Evan G. Smith", email = "egsmith@wpi.edu"},
]

description = "Coronal Hole Annotation using Semi-automatic Methods (CHASM)"
readme = "README.md"
license = {file = "COPYING"}
keywords = ["solar physics", "coronal holes", "machine learning", "data annotation", "sunpy"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]

[project.urls]
Repository = "https://github.com/CBDevelopment/CHASM"

[project.scripts]
download_data = "chasm.datasets.data_cli:main"

[project.gui-scripts]
chasm = "chasm.gui.app:run_app"

[tool.uv]
package = true

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"

[tool.uv.sources]
torch = { index = "pytorch-cu118" }
torchvision = { index = "pytorch-cu118" }

[dependency-groups]
dev = [
    "ruff>=0.14.13",
    "pytest>=8.0.0",
    "pytest-cov>=7.0.0",
    "ipykernel>=6.30.1",
    "ipywidgets>=8.1.8",
]
chronnos = [
    "drms>=0.6.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
