[project]
name = "chasm"
version = "0.1.0"
description = "CHASM"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "matplotlib>=3.10.5",
    "python-dotenv>=1.1.1",
    "sunpy[map]>=7.0.1",
]
